name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          git \
          python3-pip \
          python3-setuptools \
          python3-dev \
          zip unzip \
          openjdk-17-jdk \
          libffi-dev \
          libssl-dev \
          libsqlite3-dev \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libreadline-dev \
          libgdbm-dev \
          libbz2-dev

        pip install --upgrade pip setuptools wheel
        pip install Cython==0.29.33
        pip install buildozer

    - name: Initialize Buildozer
      run: |
        buildozer android clean

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TradingApp-APK
        path: bin/*.apk